### ISSUE TITLE
Only sidecar can read from cache

### ISSUE THREAD

**Issue by magick93** [edseymour/kinit-sidecar#2]
When in a bash session on the sidecar I can list cache entries:

```
klist
Ticket cache: FILE:/dev/shm/ccache
Default principal: MyUser@MYDOMAIN.COM
Valid starting     Expires            Service principal
09/25/18 04:32:18  09/25/18 14:32:18  krbtgt/MYDOMAIN.COM@MYDOMAIN.COM
        renew until 09/26/18 04:32:18
```

But running the same command on the application container, I get:

```
klist
klist: Credentials cache permissions incorrect (filename: /dev/shm/ccache)
```
What permissions does this need?

**Comment by edseymour** [comment]
Check the UID running in your app container ```id``` - it should match the same ```id``` of the kinit-sidecar container. Check that you are actually mounting a shared fs (e.g. ```df```) and you've configured your pod spec correctly.

**Comment by magick93** [comment]
Thanks @edseymour 
This was the problem.
